###
GET http://localhost:3333/surveys/ HTTP/1.1

###
POST http://localhost:3333/surveys HTTP/1.1
content-type: application/json

{
    "title": "Pesquisa ABC",
    "description": "Isso é uma pesquisa."
}